version: '3.3'
services:
  #MySQL Service
  monarch-mysql:
    image: mysql:8.0
    restart: always
    container_name: monarch-mysql
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./../db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

    networks:
      - monarch-net

  #App (PHP) Service
  monarch-app:
    build:
      context: ./app
      dockerfile: app.dockerfile
    image: "monarch-app"
    container_name: "monarch-app"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: "monarch-app"
      SERVICE_TAGS: prod
    working_dir: /var/www
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app/laravel-app:/var/www
      - ./php/prod.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - monarch-mysql
    networks:
      - monarch-net
    env_file: ./app/laravel-app/.env.prod

  #Nginx Servic
  monarch-webserver:
    image: nginx:alpine
    container_name: monarch-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - monarch-mysql
      - monarch-app
    volumes:
      - ./app/laravel-app:/var/www
      - ./nginx/prod/conf.d:/etc/nginx/conf.d
      - ./nginx/prod/logs:/var/log/nginx
      - ./nginx/prod/certs:/etc/nginx/certs
    networks:
      - monarch-net

  queue:
    image: monarch-app
    restart: always
    container_name: monarch-queue
    depends_on:
      - monarch-app
    environment:
      CONTAINER_ROLE: queue
    volumes:
      - ./app/laravel-app:/var/www
    env_file: ./app/laravel-app/.env.prod
    networks:
      - monarch-net

  #Phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: monarch-phpmyadmin
    depends_on:
      - monarch-mysql
    tty: true
    environment:
      PMA_HOST: monarch-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - "8085:80"
    networks:
      - monarch-net

#Docker Networks
networks:
  monarch-net:
    driver: bridge

#Volumes
volumes:
  db_data:
    driver: local
